services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: monitor
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://monitor:changeme@db:5432/monitor
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    networks:
      - backend_net

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - frontend_net

  nginx:
    image: nginx:stable
    ports:
      - "8081:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend_net
      - frontend_net

volumes:
  db_data:

networks:
  backend_net:
  frontend_net:
